spring:
  jpa:
    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              create-target: create.sql
#              action: create
#            create-source: metadata
      hibernate:
        hbm2ddl:
          delimiter: ;
        jdbc:
          lob:
            non_contextual_creation: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/dslist
    password: '1234567'
