spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/dscatalog
    password: '1234567'
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
